import type {
  Shortlist,
  ShortlistProfessorDetail,
  SavedSearch,
  ShortlistBucket,
  ContactStatus,
} from "@/types/shortlist";

// ---------------------------------------------------------------------------
// Mock Shortlists
// ---------------------------------------------------------------------------

export const mockShortlists: Shortlist[] = [
  {
    id: "sl-001",
    user_id: "u-001",
    title: "Top ML Advisors",
    description: "My top picks for machine learning PhD advisors",
    is_default: true,
    created_at: "2026-02-01T10:00:00Z",
    updated_at: "2026-03-22T14:30:00Z",
    professor_count: 3,
  },
  {
    id: "sl-002",
    user_id: "u-001",
    title: "NLP Faculty",
    description: "NLP and language model researchers",
    is_default: false,
    created_at: "2026-02-15T09:00:00Z",
    updated_at: "2026-03-20T11:00:00Z",
    professor_count: 2,
  },
  {
    id: "sl-003",
    user_id: "u-002",
    title: "Robotics Programs",
    description: null,
    is_default: true,
    created_at: "2026-03-01T08:00:00Z",
    updated_at: "2026-03-24T16:00:00Z",
    professor_count: 2,
  },
  {
    id: "sl-004",
    user_id: "u-004",
    title: "AI Safety Researchers",
    description: "Professors working on AI alignment and safety",
    is_default: false,
    created_at: "2026-03-10T12:00:00Z",
    updated_at: "2026-03-23T09:00:00Z",
    professor_count: 1,
  },
];

// ---------------------------------------------------------------------------
// Mock Shortlist Items with professor details + hexagon scores
// ---------------------------------------------------------------------------

export const mockShortlistItems: Record<string, ShortlistProfessorDetail[]> = {
  "sl-001": [
    {
      id: "sli-001",
      shortlist_id: "sl-001",
      professor_id: "prof-001",
      bucket: "target" as ShortlistBucket,
      priority: 1,
      contact_status: "sent" as ContactStatus,
      user_note:
        "Strong fit for multimodal AI research. Responded to my email last week.",
      created_at: "2026-02-01T10:05:00Z",
      updated_at: "2026-03-22T14:30:00Z",
      professor_name: "Dr. Alice Chen",
      professor_email: "achen@stanford.edu",
      institution_name: "Stanford University",
      department_name: "Computer Science",
      title: "Associate Professor",
      scholar_h_index: 42,
      scholar_citation_count: 8700,
      research_impact_score: 85,
      research_activity_score_hex: 90,
      funding_strength_score: 78,
      recruiting_signal_score_hex: 92,
      industry_opensource_score: 65,
      mentorship_culture_score: 88,
    },
    {
      id: "sli-002",
      shortlist_id: "sl-001",
      professor_id: "prof-004",
      bucket: "reach" as ShortlistBucket,
      priority: 2,
      contact_status: "drafted" as ContactStatus,
      user_note: "Graph ML lab looks amazing but very competitive.",
      created_at: "2026-02-05T11:00:00Z",
      updated_at: "2026-03-18T10:00:00Z",
      professor_name: "Dr. David Kim",
      professor_email: "dkim@cmu.edu",
      institution_name: "Carnegie Mellon University",
      department_name: "Machine Learning",
      title: "Associate Professor",
      scholar_h_index: 35,
      scholar_citation_count: 5200,
      research_impact_score: 72,
      research_activity_score_hex: 80,
      funding_strength_score: 68,
      recruiting_signal_score_hex: 45,
      industry_opensource_score: 82,
      mentorship_culture_score: 70,
    },
    {
      id: "sli-003",
      shortlist_id: "sl-001",
      professor_id: "prof-005",
      bucket: "safer" as ShortlistBucket,
      priority: 3,
      contact_status: "not_contacted" as ContactStatus,
      user_note: "Accessibility + HCI overlap with my interests.",
      created_at: "2026-02-10T09:00:00Z",
      updated_at: "2026-03-15T08:00:00Z",
      professor_name: "Dr. Elena Rodriguez",
      professor_email: "erodriguez@uw.edu",
      institution_name: "University of Washington",
      department_name: "CSE",
      title: "Full Professor",
      scholar_h_index: 47,
      scholar_citation_count: 9500,
      research_impact_score: 88,
      research_activity_score_hex: 75,
      funding_strength_score: 90,
      recruiting_signal_score_hex: 85,
      industry_opensource_score: 55,
      mentorship_culture_score: 95,
    },
  ],
  "sl-002": [
    {
      id: "sli-004",
      shortlist_id: "sl-002",
      professor_id: "prof-001",
      bucket: "target" as ShortlistBucket,
      priority: 1,
      contact_status: "replied" as ContactStatus,
      user_note: "Also on my ML list. NLP work is very relevant.",
      created_at: "2026-02-15T09:05:00Z",
      updated_at: "2026-03-20T11:00:00Z",
      professor_name: "Dr. Alice Chen",
      professor_email: "achen@stanford.edu",
      institution_name: "Stanford University",
      department_name: "Computer Science",
      title: "Associate Professor",
      scholar_h_index: 42,
      scholar_citation_count: 8700,
      research_impact_score: 85,
      research_activity_score_hex: 90,
      funding_strength_score: 78,
      recruiting_signal_score_hex: 92,
      industry_opensource_score: 65,
      mentorship_culture_score: 88,
    },
    {
      id: "sli-005",
      shortlist_id: "sl-002",
      professor_id: "prof-003",
      bucket: "not_sure" as ShortlistBucket,
      priority: 2,
      contact_status: "not_contacted" as ContactStatus,
      user_note: "Safety focus might not align with my NLP goals.",
      created_at: "2026-02-20T14:00:00Z",
      updated_at: "2026-03-18T16:00:00Z",
      professor_name: "Dr. Carol Davis",
      professor_email: null,
      institution_name: "UC Berkeley",
      department_name: "Computer Science",
      title: "Assistant Professor",
      scholar_h_index: 18,
      scholar_citation_count: 1200,
      research_impact_score: 55,
      research_activity_score_hex: 60,
      funding_strength_score: 40,
      recruiting_signal_score_hex: 65,
      industry_opensource_score: 30,
      mentorship_culture_score: 72,
    },
  ],
  "sl-003": [
    {
      id: "sli-006",
      shortlist_id: "sl-003",
      professor_id: "prof-002",
      bucket: "target" as ShortlistBucket,
      priority: 1,
      contact_status: "sent" as ContactStatus,
      user_note: "Leading robotics lab at MIT. Emailed 3 days ago.",
      created_at: "2026-03-01T08:05:00Z",
      updated_at: "2026-03-24T16:00:00Z",
      professor_name: "Dr. Bob Williams",
      professor_email: "bwilliams@mit.edu",
      institution_name: "MIT",
      department_name: "EECS",
      title: "Full Professor",
      scholar_h_index: 58,
      scholar_citation_count: 14200,
      research_impact_score: 95,
      research_activity_score_hex: 88,
      funding_strength_score: 92,
      recruiting_signal_score_hex: 42,
      industry_opensource_score: 78,
      mentorship_culture_score: 80,
    },
    {
      id: "sli-007",
      shortlist_id: "sl-003",
      professor_id: "prof-005",
      bucket: "safer" as ShortlistBucket,
      priority: 2,
      contact_status: "not_contacted" as ContactStatus,
      user_note: null,
      created_at: "2026-03-05T10:00:00Z",
      updated_at: "2026-03-20T09:00:00Z",
      professor_name: "Dr. Elena Rodriguez",
      professor_email: "erodriguez@uw.edu",
      institution_name: "University of Washington",
      department_name: "CSE",
      title: "Full Professor",
      scholar_h_index: 47,
      scholar_citation_count: 9500,
      research_impact_score: 88,
      research_activity_score_hex: 75,
      funding_strength_score: 90,
      recruiting_signal_score_hex: 85,
      industry_opensource_score: 55,
      mentorship_culture_score: 95,
    },
  ],
  "sl-004": [
    {
      id: "sli-008",
      shortlist_id: "sl-004",
      professor_id: "prof-003",
      bucket: "target" as ShortlistBucket,
      priority: 1,
      contact_status: "drafted" as ContactStatus,
      user_note: "Leading AI safety researcher at Berkeley.",
      created_at: "2026-03-10T12:05:00Z",
      updated_at: "2026-03-23T09:00:00Z",
      professor_name: "Dr. Carol Davis",
      professor_email: null,
      institution_name: "UC Berkeley",
      department_name: "Computer Science",
      title: "Assistant Professor",
      scholar_h_index: 18,
      scholar_citation_count: 1200,
      research_impact_score: 55,
      research_activity_score_hex: 60,
      funding_strength_score: 40,
      recruiting_signal_score_hex: 65,
      industry_opensource_score: 30,
      mentorship_culture_score: 72,
    },
  ],
};

// ---------------------------------------------------------------------------
// Mock Saved Searches
// ---------------------------------------------------------------------------

export const mockSavedSearches: SavedSearch[] = [
  {
    id: "ss-001",
    user_id: "u-001",
    query_text: "machine learning NLP transformer",
    filters_json: {
      institution: ["Stanford University", "MIT", "UC Berkeley"],
      min_h_index: 20,
    },
    sort_by: "h_index_desc",
    created_at: "2026-02-10T08:00:00Z",
    user_email: "alice@example.com",
  },
  {
    id: "ss-002",
    user_id: "u-001",
    query_text: "computer vision multimodal",
    filters_json: { min_h_index: 15 },
    sort_by: "relevance",
    created_at: "2026-02-20T14:00:00Z",
    user_email: "alice@example.com",
  },
  {
    id: "ss-003",
    user_id: "u-002",
    query_text: "robotics reinforcement learning",
    filters_json: {
      institution: ["MIT", "Carnegie Mellon University"],
    },
    sort_by: null,
    created_at: "2026-03-05T09:30:00Z",
    user_email: "bob@example.com",
  },
  {
    id: "ss-004",
    user_id: "u-004",
    query_text: "AI safety alignment interpretability",
    filters_json: null,
    sort_by: "created_at_desc",
    created_at: "2026-03-15T11:00:00Z",
    user_email: "david@example.com",
  },
  {
    id: "ss-005",
    user_id: "u-002",
    query_text: "graph neural networks drug discovery",
    filters_json: { min_h_index: 30 },
    sort_by: "h_index_desc",
    created_at: "2026-03-18T16:00:00Z",
    user_email: "bob@example.com",
  },
];
